package entity;
// Generated 27-09-2013 16:45:03 by Hibernate Tools 3.2.1.GA



/**
 * Enroll generated by hbm2java
 */
public class Enroll  implements java.io.Serializable {


     private int idenroll;
     private Person person;
     private User user;
     private String enrolldate;
     private String enrolltime;

    public Enroll() {
    }

	
    public Enroll(int idenroll) {
        this.idenroll = idenroll;
    }
    public Enroll(Person person, User user, String enrolldate, String enrolltime) {
       this.person = person;
       this.user = user;
       this.enrolldate = enrolldate;
       this.enrolltime = enrolltime;
    }
   
    public int getIdenroll() {
        return this.idenroll;
    }
    
    public void setIdenroll(int idenroll) {
        this.idenroll = idenroll;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEnrolldate() {
        return this.enrolldate;
    }
    
    public void setEnrolldate(String enrolldate) {
        this.enrolldate = enrolldate;
    }
    public String getEnrolltime() {
        return this.enrolltime;
    }
    
    public void setEnrolltime(String enrolltime) {
        this.enrolltime = enrolltime;
    }




}


