package entity;
// Generated 26-09-2013 19:42:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer idperson;
     private String firstname;
     private String middlename;
     private String lastname;
     private String address;
     private String birthday;
     private String expirationdate;
     private String picturepath;
     private String quarantineexpirationdate;
     private String creationdate;
     private Integer oneone;
     private Integer quarantine;
     private Integer enrolled;
     private String enrolleddate;
     private Integer hone;
     private Set guests = new HashSet(0);

    public Person() {
    }

    public Person(String firstname, String middlename, String lastname, String address, String birthday, String expirationdate, String picturepath, String quarantineexpirationdate, String creationdate, Integer oneone, Integer quarantine, Integer enrolled, String enrolleddate, Integer hone, Set guests) {
       this.firstname = firstname;
       this.middlename = middlename;
       this.lastname = lastname;
       this.address = address;
       this.birthday = birthday;
       this.expirationdate = expirationdate;
       this.picturepath = picturepath;
       this.quarantineexpirationdate = quarantineexpirationdate;
       this.creationdate = creationdate;
       this.oneone = oneone;
       this.quarantine = quarantine;
       this.enrolled = enrolled;
       this.enrolleddate = enrolleddate;
       this.hone = hone;
       this.guests = guests;
    }
    
    public Person(String firstname, String middlename, String lastname, String address, String birthday, String expirationdate, String picturepath, String quarantineexpirationdate, String creationdate, Integer oneone, Integer quarantine, Integer enrolled, String enrolleddate, Integer hone) {
       this.firstname = firstname;
       this.middlename = middlename;
       this.lastname = lastname;
       this.address = address;
       this.birthday = birthday;
       this.expirationdate = expirationdate;
       this.picturepath = picturepath;
       this.quarantineexpirationdate = quarantineexpirationdate;
       this.creationdate = creationdate;
       this.oneone = oneone;
       this.quarantine = quarantine;
       this.enrolled = enrolled;
       this.enrolleddate = enrolleddate;
       this.hone = hone;
    }
   
    public Integer getIdperson() {
        return this.idperson;
    }
    
    public void setIdperson(Integer idperson) {
        this.idperson = idperson;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    public String getExpirationdate() {
        return this.expirationdate;
    }
    
    public void setExpirationdate(String expirationdate) {
        this.expirationdate = expirationdate;
    }
    public String getPicturepath() {
        return this.picturepath;
    }
    
    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath;
    }
    public String getQuarantineexpirationdate() {
        return this.quarantineexpirationdate;
    }
    
    public void setQuarantineexpirationdate(String quarantineexpirationdate) {
        this.quarantineexpirationdate = quarantineexpirationdate;
    }
    public String getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(String creationdate) {
        this.creationdate = creationdate;
    }
    public Integer getOneone() {
        return this.oneone;
    }
    
    public void setOneone(Integer oneone) {
        this.oneone = oneone;
    }
    public Integer getQuarantine() {
        return this.quarantine;
    }
    
    public void setQuarantine(Integer quarantine) {
        this.quarantine = quarantine;
    }
    public Integer getEnrolled() {
        return this.enrolled;
    }
    
    public void setEnrolled(Integer enrolled) {
        this.enrolled = enrolled;
    }
    public String getEnrolleddate() {
        return this.enrolleddate;
    }
    
    public void setEnrolleddate(String enrolleddate) {
        this.enrolleddate = enrolleddate;
    }
    public Integer getHone() {
        return this.hone;
    }
    
    public void setHone(Integer hone) {
        this.hone = hone;
    }
    public Set getGuests() {
        return this.guests;
    }
    
    public void setGuests(Set guests) {
        this.guests = guests;
    }




}


