/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author patrick
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Pane = new javax.swing.JPanel();
        søgeFelt_TextField = new javax.swing.JTextField();
        søg_Button = new javax.swing.JButton();
        valgtePerson_Pane = new javax.swing.JPanel();
        navn_Label = new javax.swing.JLabel();
        høne_Label = new javax.swing.JLabel();
        Gæster_Label = new javax.swing.JLabel();
        billed_Pane = new javax.swing.JPanel();
        billed_Label = new javax.swing.JLabel();
        indskrivning_Label = new javax.swing.JLabel();
        indTidspunkt_Label = new javax.swing.JLabel();
        navnFelt_Label = new javax.swing.JLabel();
        høneFelt_Label = new javax.swing.JLabel();
        indskrivningFelt_Label = new javax.swing.JLabel();
        indTidspunktFelt_Label = new javax.swing.JLabel();
        indskrivn_Button = new javax.swing.JButton();
        redigerIndskrivning_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        fundnePersoner_Pane = new javax.swing.JPanel();
        personer_ScrollPane = new javax.swing.JScrollPane();
        personer_List = new javax.swing.JList();
        bund_Pane = new javax.swing.JPanel();
        dato_Label = new javax.swing.JLabel();
        menuBar_MenuBar = new javax.swing.JMenuBar();
        filer_Menu = new javax.swing.JMenu();
        nulstil_MenuItem = new javax.swing.JMenuItem();
        administrer_Menu = new javax.swing.JMenu();
        opretPerson_MenuItem = new javax.swing.JMenuItem();
        redigerPerson_MenuItem = new javax.swing.JMenuItem();
        sep1_Seperator = new javax.swing.JPopupMenu.Separator();
        indstillinger_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISM");
        setMaximumSize(new java.awt.Dimension(912, 497));
        setMinimumSize(new java.awt.Dimension(912, 497));
        setResizable(false);

        søg_Button.setText("Søg");

        valgtePerson_Pane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valgte person", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        navn_Label.setText("Navn:");

        høne_Label.setText("Høne:");

        Gæster_Label.setText("Gæster:");

        billed_Pane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout billed_PaneLayout = new javax.swing.GroupLayout(billed_Pane);
        billed_Pane.setLayout(billed_PaneLayout);
        billed_PaneLayout.setHorizontalGroup(
            billed_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        billed_PaneLayout.setVerticalGroup(
            billed_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        billed_Label.setText("Billed:");

        indskrivning_Label.setText("Indskriver:");

        indTidspunkt_Label.setText("Ind tidspunkt:");

        navnFelt_Label.setText("Patrick Kann");

        høneFelt_Label.setText("Ja");

        indskrivningFelt_Label.setText("Mallica");

        indTidspunktFelt_Label.setText("21:41");

        indskrivn_Button.setText("Indskriv");

        redigerIndskrivning_Button.setText("Rediger indskrivning");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout valgtePerson_PaneLayout = new javax.swing.GroupLayout(valgtePerson_Pane);
        valgtePerson_Pane.setLayout(valgtePerson_PaneLayout);
        valgtePerson_PaneLayout.setHorizontalGroup(
            valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valgtePerson_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(valgtePerson_PaneLayout.createSequentialGroup()
                        .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(navn_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(høne_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indskrivning_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indTidspunkt_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(navnFelt_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(høneFelt_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indskrivningFelt_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indTidspunktFelt_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(valgtePerson_PaneLayout.createSequentialGroup()
                        .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(valgtePerson_PaneLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(billed_Label)
                                    .addComponent(billed_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Gæster_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(valgtePerson_PaneLayout.createSequentialGroup()
                                .addComponent(indskrivn_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redigerIndskrivning_Button)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        valgtePerson_PaneLayout.setVerticalGroup(
            valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valgtePerson_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navn_Label)
                    .addComponent(navnFelt_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(høne_Label)
                    .addComponent(høneFelt_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indskrivning_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indskrivningFelt_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indTidspunkt_Label)
                    .addComponent(indTidspunktFelt_Label))
                .addGap(18, 18, 18)
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gæster_Label)
                    .addComponent(billed_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(billed_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valgtePerson_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indskrivn_Button)
                    .addComponent(redigerIndskrivning_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fundnePersoner_Pane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fundne personer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        personer_List.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        personer_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        personer_ScrollPane.setViewportView(personer_List);

        javax.swing.GroupLayout fundnePersoner_PaneLayout = new javax.swing.GroupLayout(fundnePersoner_Pane);
        fundnePersoner_Pane.setLayout(fundnePersoner_PaneLayout);
        fundnePersoner_PaneLayout.setHorizontalGroup(
            fundnePersoner_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundnePersoner_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personer_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        fundnePersoner_PaneLayout.setVerticalGroup(
            fundnePersoner_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundnePersoner_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personer_ScrollPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout main_PaneLayout = new javax.swing.GroupLayout(main_Pane);
        main_Pane.setLayout(main_PaneLayout);
        main_PaneLayout.setHorizontalGroup(
            main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_PaneLayout.createSequentialGroup()
                        .addComponent(valgtePerson_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fundnePersoner_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(main_PaneLayout.createSequentialGroup()
                        .addComponent(søgeFelt_TextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(søg_Button)))
                .addContainerGap())
        );
        main_PaneLayout.setVerticalGroup(
            main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(søgeFelt_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(søg_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valgtePerson_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fundnePersoner_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bund_Pane.setBackground(new java.awt.Color(102, 102, 102));

        dato_Label.setForeground(new java.awt.Color(255, 255, 255));
        dato_Label.setText("Dato: 22-08-2013");

        javax.swing.GroupLayout bund_PaneLayout = new javax.swing.GroupLayout(bund_Pane);
        bund_Pane.setLayout(bund_PaneLayout);
        bund_PaneLayout.setHorizontalGroup(
            bund_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bund_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dato_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bund_PaneLayout.setVerticalGroup(
            bund_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bund_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dato_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filer_Menu.setText("Filer");

        nulstil_MenuItem.setText("Daglig nulstilling");
        filer_Menu.add(nulstil_MenuItem);

        menuBar_MenuBar.add(filer_Menu);

        administrer_Menu.setText("Administrer");

        opretPerson_MenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        opretPerson_MenuItem.setText("Opret person");
        administrer_Menu.add(opretPerson_MenuItem);

        redigerPerson_MenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        redigerPerson_MenuItem.setText("Rediger person");
        administrer_Menu.add(redigerPerson_MenuItem);
        administrer_Menu.add(sep1_Seperator);

        indstillinger_MenuItem.setText("Indstillinger");
        administrer_Menu.add(indstillinger_MenuItem);

        menuBar_MenuBar.add(administrer_Menu);

        setJMenuBar(menuBar_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bund_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bund_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gæster_Label;
    private javax.swing.JMenu administrer_Menu;
    private javax.swing.JLabel billed_Label;
    private javax.swing.JPanel billed_Pane;
    private javax.swing.JPanel bund_Pane;
    private javax.swing.JLabel dato_Label;
    private javax.swing.JMenu filer_Menu;
    private javax.swing.JPanel fundnePersoner_Pane;
    private javax.swing.JLabel høneFelt_Label;
    private javax.swing.JLabel høne_Label;
    private javax.swing.JLabel indTidspunktFelt_Label;
    private javax.swing.JLabel indTidspunkt_Label;
    private javax.swing.JButton indskrivn_Button;
    private javax.swing.JLabel indskrivningFelt_Label;
    private javax.swing.JLabel indskrivning_Label;
    private javax.swing.JMenuItem indstillinger_MenuItem;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_Pane;
    private javax.swing.JMenuBar menuBar_MenuBar;
    private javax.swing.JLabel navnFelt_Label;
    private javax.swing.JLabel navn_Label;
    private javax.swing.JMenuItem nulstil_MenuItem;
    private javax.swing.JMenuItem opretPerson_MenuItem;
    private javax.swing.JList personer_List;
    private javax.swing.JScrollPane personer_ScrollPane;
    private javax.swing.JButton redigerIndskrivning_Button;
    private javax.swing.JMenuItem redigerPerson_MenuItem;
    private javax.swing.JPopupMenu.Separator sep1_Seperator;
    private javax.swing.JButton søg_Button;
    private javax.swing.JTextField søgeFelt_TextField;
    private javax.swing.JPanel valgtePerson_Pane;
    // End of variables declaration//GEN-END:variables
}
