/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.HoneUser;

/**
 *
 * @author pkann
 */
public class OpretHoneGUI extends javax.swing.JDialog {

    private HoneUser honeUser;
    
    public OpretHoneGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setHoneUser(HoneUser honeUser) {
        this.honeUser = honeUser;
    }
    
    private boolean isFieldsFilledOut() {
        if(user_TextField.getText().isEmpty() || pass_TextField.getText().isEmpty() || confirmPass_TextField.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }
    
    private void reset() {
        user_TextField.setText("");
        pass_TextField.setText("");
        confirmPass_TextField.setText("");
        admin_CheckBox.getModel().setSelected(false);
        reserve_CheckBox.getModel().setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Pane = new javax.swing.JPanel();
        info_Pane = new javax.swing.JPanel();
        info_Label = new javax.swing.JLabel();
        field_Pane = new javax.swing.JPanel();
        user_Label = new javax.swing.JLabel();
        user_TextField = new javax.swing.JTextField();
        pass_TextField = new javax.swing.JTextField();
        confirmPass_TextField = new javax.swing.JTextField();
        pass_Label = new javax.swing.JLabel();
        confirmPass_Label = new javax.swing.JLabel();
        tool_Pane = new javax.swing.JPanel();
        opretHone_Button = new javax.swing.JButton();
        reserve_CheckBox = new javax.swing.JCheckBox();
        splitter1_Label = new javax.swing.JLabel();
        admin_CheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opret høne");
        setMaximumSize(new java.awt.Dimension(500, 263));
        setMinimumSize(new java.awt.Dimension(500, 263));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        main_Pane.setBackground(java.awt.Color.darkGray);

        info_Label.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        info_Label.setText("Opsæt høne brugeren");

        javax.swing.GroupLayout info_PaneLayout = new javax.swing.GroupLayout(info_Pane);
        info_Pane.setLayout(info_PaneLayout);
        info_PaneLayout.setHorizontalGroup(
            info_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_PaneLayout.setVerticalGroup(
            info_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        user_Label.setText("E-mail(Bruger):");

        pass_Label.setText("Kodeord:");

        confirmPass_Label.setText("Bekræft kode:");

        javax.swing.GroupLayout field_PaneLayout = new javax.swing.GroupLayout(field_Pane);
        field_Pane.setLayout(field_PaneLayout);
        field_PaneLayout.setHorizontalGroup(
            field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(field_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_Label)
                    .addComponent(pass_Label)
                    .addComponent(confirmPass_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_TextField)
                    .addComponent(user_TextField)
                    .addComponent(confirmPass_TextField))
                .addContainerGap())
        );
        field_PaneLayout.setVerticalGroup(
            field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(field_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_Label)
                    .addComponent(user_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(field_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPass_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPass_Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        opretHone_Button.setText("Opret høne");
        opretHone_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opretHone_ButtonActionPerformed(evt);
            }
        });

        reserve_CheckBox.setText("Reserver");

        splitter1_Label.setText("|");

        admin_CheckBox.setText("Admin");

        javax.swing.GroupLayout tool_PaneLayout = new javax.swing.GroupLayout(tool_Pane);
        tool_Pane.setLayout(tool_PaneLayout);
        tool_PaneLayout.setHorizontalGroup(
            tool_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tool_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opretHone_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserve_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitter1_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_CheckBox)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        tool_PaneLayout.setVerticalGroup(
            tool_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tool_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tool_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opretHone_Button)
                    .addComponent(reserve_CheckBox)
                    .addComponent(splitter1_Label)
                    .addComponent(admin_CheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout main_PaneLayout = new javax.swing.GroupLayout(main_Pane);
        main_Pane.setLayout(main_PaneLayout);
        main_PaneLayout.setHorizontalGroup(
            main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tool_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_PaneLayout.setVerticalGroup(
            main_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tool_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opretHone_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opretHone_ButtonActionPerformed
        if(isFieldsFilledOut()) {
            if(pass_TextField.getText().equals(confirmPass_TextField.getText())) {
                String user = user_TextField.getText();
                String pass = pass_TextField.getText();
                boolean admin = admin_CheckBox.getModel().isSelected();
                boolean reserve = reserve_CheckBox.getModel().isSelected();
                
                honeUser = new HoneUser(user, pass, admin, reserve);
                
                dispose();
            } else {
                System.out.println("Password is not confirmed");
            }
        }
    }//GEN-LAST:event_opretHone_ButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        reset();
    }//GEN-LAST:event_formWindowClosed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OpretHoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OpretHoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OpretHoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OpretHoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                OpretHoneGUI dialog = new OpretHoneGUI(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox admin_CheckBox;
    private javax.swing.JLabel confirmPass_Label;
    private javax.swing.JTextField confirmPass_TextField;
    private javax.swing.JPanel field_Pane;
    private javax.swing.JLabel info_Label;
    private javax.swing.JPanel info_Pane;
    private javax.swing.JPanel main_Pane;
    private javax.swing.JButton opretHone_Button;
    private javax.swing.JLabel pass_Label;
    private javax.swing.JTextField pass_TextField;
    private javax.swing.JCheckBox reserve_CheckBox;
    private javax.swing.JLabel splitter1_Label;
    private javax.swing.JPanel tool_Pane;
    private javax.swing.JLabel user_Label;
    private javax.swing.JTextField user_TextField;
    // End of variables declaration//GEN-END:variables
}
